name: m_cal
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pandas
  - numpy
  - openpyxl
  - plotly
  - requests
  - pip:
      - python-dotenv
      - openai
      - streamlit
      - fpdf2
      - pdfplumber