import json
from openai import OpenAI
import os
import re
from src.dirs import DIRS
from typing import Optional, Dict, Any

# get openai client
def get_openai_client():
    return OpenAI(api_key=os.environ["OPENAI_API_KEY"])

# ===============================================================
# 📦 loading data from receipt into json
# ===============================================================
def loading_data_from_receipt_into_json(prepared_receipt: str) -> None:
    
    # Send an image of a receipt to the OpenAI API for text extraction,
    # receive a JSON-formatted response, and save it locally as 'receipt_raw.json'.

    # Args:
    #   prepared_receipt (str): Base64-encoded image of the receipt, formatted as
    #                            'data:image/jpg;base64,...'.

    # Returns:
    #     None: The function saves the parsed receipt JSON to a file in 
    #           DIRS['temporary_json_from_receipt'].

    # 🛡️Gives:
    #   an empty dataframe if we upload an incorrect photo
    
    
    response = get_openai_client().chat.completions.create(
        # model="gpt-4o",
        model="gpt-4o-mini",
        temperature=0,
        messages=[
            {
                "role": "user",
                "content": [
                    {
                        "type": "text",
                        "text": """
    Wyciągnij informacje zawarte na paragonie z Restauracji w McDonald's w Polsce.
    Dane przedstaw w formacie JSON.
    Oczekuję informacji dotyczących nazw produtków, ilości, kwoty za poszczególne produkty oraz łącznej kwoty za cały paragon.
    Niektóre produkty w systemie fiskalnym mogą mieć niekonwencjonalne nazwy.
    Pod napisem "PARAGON FISKALNY" znajdują się produkty jeden pod drugim.
    Od lewej jest jego nazwa, po prawej ilość i należność.
    „Jeśli w nazwie produktu występuje liczba (np. Tenders 3, Tenders 5), traktuj ją jako część nazwy np: "Nuggets 6", "Tenders 3", etc. traktuj je jako 1 produkt.
    Dodatkowo potrzebuję informacji o:
    - dacie: rok, misiąć i dzień oraz godzinę zakupu.
    - Miejscu zakupu: miasto, ulica.
    Usuń z wszystkich kluczy i wartości dokładnie te znaki: kropkę (.), gwiazdkę (*), podłogę (_).
    Jeżeli podłoga (_) jest między literami zastą spacją ( )
    Nie zostawiaj żadnego z nich.
    Przykładowa struktura (na paragonie będą się znajdować różne produkty to przykład):
    {
    {
    "lody w wafelku z polewą karmelową": {
        "ilość": ...,
        "kwota": ...
    },
    "cheeseburger": {
        "ilość": ...,
        "kwota": ...
    },
    "lody w kubku z polewą truskawkową": {
        "ilość": ...,
        "kwota": ...
    },
    "Big Mac": {
        "ilość": ...,
        "kwota": ...
    },
    "łączna kwota za paragon": ...,
    "data": "yyyy-mm-dd",
    "godzina": "hh:mm",
    "miasto": "...",
    "ulica": "..."
    }
    JEŻELI OBRAZ NIE BĘDZIE ZAWIERAŁ INFORMACJI STWÓRZ PUSTEGO
    tylko dane jako JSON, bez żadnych komentarzy
    """
                    },
                    {
                        "type": "image_url",
                        "image_url": {
                            "url": prepared_receipt,
                            "detail": "high"
                        },
                    },
                ],
            }
        ],
    )

        # saving the calorie table as json
        # temporary_json_from_receipt_PATH
    json_from_receipt = response.choices[0].message.content.replace('```json','').replace('```','').strip()
    with open(DIRS['temporary_json_from_receipt']/f'receipt_raw.json', 'w') as f:
            f.write(json_from_receipt)

# ===============================================================
# 📦 PARSIN JSON_RAW
# ===============================================================
def parsing_data_from_receipt_raw_into_json() -> Optional[Dict[str, Any]]:
    # Load the raw receipt JSON generated by OpenAI, send it back to the model for 
    # normalization (e.g., mapping Polish product names to English equivalents),
    # and save the cleaned version as 'receipt_parsed.json'.

    # Returns:
    #    Optional[Dict[str, Any]]: Parsed and cleaned JSON data if successful, 
    #                              otherwise None if the file doesn't exist or is invalid.

    # 🛡️Gives:
    #    an empty dataframe if the json from the previous function is empty

    # Path to the raw JSON file
    receipt_raw_path = DIRS['temporary_json_from_receipt'] / "receipt_raw.json"

    # 🔹 If the file does not exist, stop gracefully
    if not receipt_raw_path.exists():
        return None

    # 🔹 Try loading the raw JSON (first time) to prepare it as a string for the prompt
    try:
        with open(receipt_raw_path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except (json.JSONDecodeError, FileNotFoundError):
        # If the file is empty or corrupted — stop without raising an error
        return None

    # 🔹 Convert JSON to string for prompt input
    data_str_for_AI_maping = json.dumps(data, indent=2, ensure_ascii=False)

    # 🔹 Reload the file (second read — as in the original code)
    with open(receipt_raw_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    prompt = f"""
    Masz poniższy JSON z danymi pochodzącymi z paragonu z restauracji McDonald's Polska:
    {data_str_for_AI_maping}

    Twoim zadaniem jest:
    1. Zamienić TYLKO nazwy produktów (klucze na najwyższym poziomie) na ich czytelne odpowiedniki w języku polskim.
    2. Nie zmieniaj żadnych podstruktur:
    - Klucze "ilość" i "kwota" muszą pozostać takie same.
    - Wartości tych kluczy pozostają bez zmian.
    3. Nie zmieniaj ani nie ruszaj pól: "łączna kwota za paragon", "data", "godzina", "miasto", "ulica".
    4. Jeżeli w nazwie produktu występują litery "HM" — usuń ten produkt z wynikowego JSON-a.
    5. Nie twórz nowych produktów ani nie poprawiaj nazw istniejących (np. NIE zmieniaj "Cheeseburger" → "McCheeseburger").
    6. Zwróć TYLKO poprawiony JSON, bez żadnych komentarzy ani tekstu opisu.

    Mapowanie nazw produktów:
    "FL Wan Lio Czek": "McFlurry o smaku waniliowym KitKat z polewą o smaku czekoladowym",
    "WrapChrup Klas": "McWrap Chrupiący Klasyczny",
    "Wrap Chrup Klas": "McWrap Chrupiący Klasyczny",
    "WrapBekDeLuxChr": "McWrap Chrupiący Bekon Deluxe"
    "McRoyal M": "McRoyal"
    "Frytki Mal Pol": "Frytki Małe",
    "FrytkiMala Por.": "Frytki Małe",
    "Frytki M": "Frytki Średnie",
    "Frytki Srednie": "Frytki Średnie",
    "Frytki Duze": "Frytki Duże"
    "Sos Smietanowy": "Sos Śmietanowy",
    "Tenders 3": "Chicken Tenders 3 szt.",
    "Sos Siri Mayo": "Sos Sriracha Mayo",
    "Kanapka Chikker": "Chikker",
    "Ketchup Platny": "Ketchup",
    "Kaj Wie Wiel": "Wieloziarnista Podwójna Kajzerka Wieprzowa DeLuxe",
    "Kaj Wie Wiel M": "Wieloziarnista Podwójna Kajzerka Wieprzowa DeLuxe",
    "MuffinWiepJajko": "McMuffin Wieprzowy z Jajkiem",
    "Wafel Czekolada": "Lody o smaku waniliowym z polewą o smaku czekoladowym",
    "Kubek Czekolada": "Lody o smaku waniliowym z polewą o smaku czekoladowym",
    "Kubek Karmel": "Lody o smaku waniliowym z polewą karmelową",
    "Wafel Karmel": "Lody o smaku waniliowym z polewą karmelową",
    "Jalapeno Burger": "Jalapeño Burger",
    "Sos SlodkoKwasny": "Sos Słodko-Kwaśny",
    "0,25 CocaColaStr": "Coca-Cola 0,25l"
    "0,4l Coca Cola": "Coca-Cola 0,4l",
    "0,4l Coca Cola M": "Coca-Cola 0,4l",
    "0,2l Cappucino": "Cappuccino 0,2l",
    "MuffinWiepJajko": "McMuffin Wieprzowy z Jajkiem",
    "0,4 CarLatMacch": "Caramel Latte Macchiato 0,4l",
    "Drwala": "Burger Drwala",
    "Zakrencone Frytki": "Frytki Zakręcone"

    JEŻELI JSON NIE BĘDZIE ZAWIERAŁ INFORMACJI STWÓRZ PUSTEGO JSON
    Zwróć poprawiony JSON.
    """

    response = get_openai_client().chat.completions.create(
    model="gpt-4o-mini",
    messages=[{"role": "user", "content": prompt}],
    )
    new_json_text = response.choices[0].message.content

    # Extract JSON object from model's text response
    match = re.search(r'(\{.*\})', new_json_text, re.DOTALL)
    if match:
        json_only = match.group(1)
        new_data = json.loads(json_only)
    else:
        raise ValueError("Nie znaleziono poprawnego JSON-a w odpowiedzi modelu")

    # Save the parsed data to a new file
    with open(DIRS['temporary_json_parsed']/"receipt_parsed.json", "w", encoding="utf-8") as f:
        json.dump(new_data, f, indent=2, ensure_ascii=False)